version: "3.4"

services:
  examplegorillamuxanddocker:
    image: examplegorillamuxanddocker
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ../fake-pokemon-db
        target: /app/containerData
